### ISSUE TITLE
No longer working, showing blank screen (Probably due to Dart 2 strong mode)

### ISSUE THREAD

**Issue by MaskyS** [mikemimik/flutter-calendar#32]
This plugin's example is no longer working, I'm getting a type error as follows and a blank screen:

```E/flutter ( 4856): [ERROR:topaz/lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
E/flutter ( 4856): type '(List<Map<String, dynamic>>) => List<Event>' is not a subtype of type '(dynamic) => List<DataModel>'
E/flutter ( 4856): #0      new DataController (package:calendar/src/data/data_controller.dart:24:22)
E/flutter ( 4856): #1      dataController (file:///home/maskys/flutter-calendar/example/lib/main.dart:121:37)
E/flutter ( 4856): #2      dataController (file:///home/maskys/flutter-calendar/example/lib/main.dart:121:16)
E/flutter ( 4856): #3      main (file:///home/maskys/flutter-calendar/example/lib/main.dart:138:27)```

Trying to change the type hint of `renderEventsHandler` to `List<Event>` doesn't work either, screen is still blank.

**Comment by mikemimik** [comment]
@MaskyS Sorry that it's been so long since I've updated this. I have two working copies currently, one with updated logic to make this module more flexible and one to update it to dart2. I've been busy with other projects and this one has taken a back seat at the moment. I'll do my best to get it operational as quickly as I can. Thanks for opening this issue. I'll track my progress, with regards to dart2 specifically, against this issue.

**Comment by mikemimik** [comment]
I've scheduled time for this at the end of August.

**Comment by linuxeasy** [comment]
https://github.com/mikemimik/flutter-calendar/blob/0ecbcba269346e40462a46870db1c401ae7629c7/example/lib/main.dart#L106

changing
`List<Event> parseDataHandler(List<Map<String, dynamic>> payload) `

to 

`List<Event> parseDataHandler(dynamic payload) `

fixes the calendar not being loaded issue :)
